### ISSUE TITLE
Get java.lang.NullPointerException when hbase table union parquet table or json table

### ISSUE THREAD

**Issue by pzzs** [Huawei-Spark/hbase#12]
[1] Hbase Table 

```
grade            int
class            int
subject          string  
teacher _name    string
teacher _age     int

keyCols : grade,class,subject
```

SQL ：
···
CREATE TABLE spark_teacher_3key(grade int, class int, subject string, teacher_name string, teacher_age int, PRIMARY KEY (grade, class, subject)) MAPPED BY (hbase_teacher_3key, COLS=[teacher_name=teacher.name, teacher_age=teacher.age]);
···

Data

```
1,1,subject_1,teacher_1_1_1,25
1,1,subject_2,teacher_1_2_1,25
1,1,subject_3,teacher_1_3_1,25
1,1,subject_4,teacher_1_4_1,25
1,1,subject_5,teacher_1_5_1,25
1,2,subject_1,teacher_1_1_1,25
1,2,subject_2,teacher_1_2_1,25
1,2,subject_3,teacher_1_3_1,25
1,2,subject_4,teacher_1_4_1,25
1,2,subject_5,teacher_1_5_1,25
1,3,subject_1,teacher_1_1_1,25
1,3,subject_2,teacher_1_2_1,25
...
...
```

[2] Parquet table 

```
[name,string,]
[favorite_color,string,]
[favorite_numbers,array<int>,]
```

SQL 

```
CREATE TEMPORARY TABLE parquetTable
USING org.apache.spark.sql.parquet
OPTIONS (
  path "file:///opt/cluster/SparkOnHabase/spark/examples/src/main/resources/users.parquet"
)
```

[3] QuerySQL 

```
select * from (select teacher_name from spark_teacher_3key t1 union all select name from parquetTable) t3;
```

Exception Info

```
spark-hbaseql> select * from (select teacher_name from spark_teacher_3key t1 union all select name from parquetTable) t3;                          
java.lang.NullPointerException
        at org.apache.spark.sql.hbase.execution.AddCoprocessor.org$apache$spark$sql$hbase$execution$AddCoprocessor$$generateNewSubplan(AddCoprocessor.scala:58)
        at org.apache.spark.sql.hbase.execution.AddCoprocessor$$anonfun$2$$anonfun$3.apply(AddCoprocessor.scala:99)
        at org.apache.spark.sql.hbase.execution.AddCoprocessor$$anonfun$2$$anonfun$3.apply(AddCoprocessor.scala:97)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at org.apache.spark.sql.hbase.execution.AddCoprocessor$$anonfun$2.applyOrElse(AddCoprocessor.scala:97)
        at org.apache.spark.sql.hbase.execution.AddCoprocessor$$anonfun$2.applyOrElse(AddCoprocessor.scala:82)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:286)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:286)
        at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:51)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:285)
        at org.apache.spark.sql.hbase.execution.AddCoprocessor.apply(AddCoprocessor.scala:82)
        at org.apache.spark.sql.hbase.execution.AddCoprocessor.apply(AddCoprocessor.scala:25)
        at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1$$anonfun$apply$1.apply(RuleExecutor.scala:61)
        at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1$$anonfun$apply$1.apply(RuleExecutor.scala:59)
        at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:51)
        at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:60)
        at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:34)
        at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1.apply(RuleExecutor.scala:59)
        at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1.apply(RuleExecutor.scala:51)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:51)
        at org.apache.spark.sql.SQLContext$QueryExecution.executedPlan$lzycompute(SQLContext.scala:936)
        at org.apache.spark.sql.SQLContext$QueryExecution.executedPlan(SQLContext.scala:936)
        at org.apache.spark.sql.DataFrame.collect(DataFrame.scala:1255)
        at org.apache.spark.sql.hbase.HBaseSQLCliDriver$.process(HBaseSQLCliDriver.scala:130)
        at org.apache.spark.sql.hbase.HBaseSQLCliDriver$.processLine(HBaseSQLCliDriver.scala:113)
        at org.apache.spark.sql.hbase.HBaseSQLCliDriver$.main(HBaseSQLCliDriver.scala:91)
        at org.apache.spark.sql.hbase.HBaseSQLCliDriver.main(HBaseSQLCliDriver.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:664)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:169)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:192)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:111)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

when i test 'union' using hbase table and json table, this execption happended again.

**Comment by xinyunh** [comment]
Fixed and merged into master (https://github.com/Huawei-Spark/hbase/commit/ef3bf69472d33fadcefc8407221162592acf2bbe)

Thanks!
