### ISSUE TITLE
Get ArrayIndexOutOfBoundsException when running "select * from table" after relate hbase table.

### ISSUE THREAD

**Issue by pzzs** [Huawei-Spark/hbase#13]
Hbase table 

```
SQL :

  create 'test','student'
  put 'test','1001','student:name','Mary'
  put 'test','1001','student:age','21'
  put 'test','1002','student:name','Jack'
  put 'test','1002','student:age','22'
  put 'test','1003','student:name','John'
  put 'test','1003','student:age','23'
  put 'test','1004','student:name','John'
  put 'test','1004','student:age','22'

Data :
rowKey  student:name  student:age 
1001    Mary                  21             
1002    Jack                  22             
1003    John                  23    
1004    John                  22  
```

Relate test

Case1 --> right

```
student_num    string
student_name  string
student_age     string

CREATE TABLE spark_test_string(student_num string, student_name string, student_age string, PRIMARY KEY (student_num)) MAPPED BY (test, COLS=[student_name=student.name, student_age=student.age]); 

Info :
spark-hbaseql> select * from spark_test_string;
[1001,Mary,21]
[1002,Jack,22]
[1003,John,23]
[1004,John,22]
```

Case2 --> Error

```
student_num    int
student_name  string
student_age     int

CREATE TABLE spark_test_int(student_num int, student_name string, student_age int, PRIMARY KEY (student_num)) MAPPED BY (test, COLS=[student_name=student.name, student_age=student.age]); 

Info :
spark-hbaseql> select * from spark_test_int;
15/07/13 16:02:48 WARN TaskSetManager: Lost task 0.0 in stage 2.0 (TID 2, 9.91.8.153): java.lang.ArrayIndexOutOfBoundsException: 36
        at org.apache.spark.sql.hbase.util.BytesUtils$$anonfun$toInt$1.apply$mcVI$sp(BytesUtils.scala:76)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:141)
        at org.apache.spark.sql.hbase.util.BytesUtils$.toInt(BytesUtils.scala:75)
        at org.apache.spark.sql.hbase.util.DataTypeUtils$.setRowColumnFromHBaseRawType(DataTypeUtils.scala:94)
        at org.apache.spark.sql.hbase.HBaseRelation.org$apache$spark$sql$hbase$HBaseRelation$$setColumn(HBaseRelation.scala:885)
        at org.apache.spark.sql.hbase.HBaseRelation$$anonfun$buildRow$1.apply(HBaseRelation.scala:969)
        at org.apache.spark.sql.hbase.HBaseRelation$$anonfun$buildRow$1.apply(HBaseRelation.scala:965)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at org.apache.spark.sql.hbase.HBaseRelation.buildRow(HBaseRelation.scala:964)
        at org.apache.spark.sql.hbase.HBaseSQLReaderRDD$$anonfun$3.apply(HBaseSQLReaderRDD.scala:72)
        at org.apache.spark.sql.hbase.HBaseSQLReaderRDD$$anonfun$3.apply(HBaseSQLReaderRDD.scala:72)
        at org.apache.spark.sql.hbase.HBaseSQLReaderRDD$$anon$1.next(HBaseSQLReaderRDD.scala:188)
        at org.apache.spark.sql.hbase.HBaseSQLReaderRDD$$anon$1.next(HBaseSQLReaderRDD.scala:170)
        at org.apache.spark.InterruptibleIterator.next(InterruptibleIterator.scala:43)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:103)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:47)
        at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)
        at scala.collection.AbstractIterator.to(Iterator.scala:1157)
        at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:265)
        at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1157)
        at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:252)
        at scala.collection.AbstractIterator.toArray(Iterator.scala:1157)
        at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$12.apply(RDD.scala:885)
        at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$12.apply(RDD.scala:885)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1765)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1765)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:63)
        at org.apache.spark.scheduler.Task.run(Task.scala:70)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:722)
```

when type of student_num ,student_age, i get this execption.

**Comment by yzhou2001** [comment]
@DoingDone9 This is not a bug, because we now only do binary conversion to numerals, and not string conversion to numerals. This approach has performance advantage, but results limited support of schema-on-read capability.

In the future, we could add this support based upon a configuration flag.
