### ISSUE TITLE
Filter Error(DataFrame): Get ArrayIndexOutOfBoundsException when set spark.sql.hbase.coprocessor and spark.sql.hbase.customfilter "false"

### ISSUE THREAD

**Issue by pzzs** [Huawei-Spark/hbase#15]
[1] Hbase Table 

```
grade            int
class            int
subject          string  
teacher _name    string
teacher _age     int

keyCols : grade,class,subject
```

SQL ：

```
CREATE TABLE spark_teacher_3key(grade int, class int, subject string, teacher_name string, teacher_age int, PRIMARY KEY (grade, class, subject)) MAPPED BY (hbase_teacher_3key, COLS=[teacher_name=teacher.name, teacher_age=teacher.age]);
```

Data

```
1,1,subject_1,teacher_1_1_1,25
1,1,subject_2,teacher_1_2_1,25
1,1,subject_3,teacher_1_3_1,25
1,1,subject_4,teacher_1_4_1,25
1,1,subject_5,teacher_1_5_1,25
1,2,subject_1,teacher_1_1_1,25
1,2,subject_2,teacher_1_2_1,25
1,2,subject_3,teacher_1_3_1,25
1,2,subject_4,teacher_1_4_1,25
1,2,subject_5,teacher_1_5_1,25
1,3,subject_1,teacher_1_1_1,25
1,3,subject_2,teacher_1_2_1,25
...
...
```

[3] DataFrame Code

```
val hbaseContext: HBaseSQLContext = new HBaseSQLContext(sc)
hbaseContext.setConf("spark.sql.hbase.coprocessor", "false");
hbaseContext.setConf("spark.sql.hbase.customfilter", "false");
val teachers: DataFrame = hbaseContext.sql("Select * from spark_teacher_3key")

teachers.filter(teachers.col("grade").gt(2).and(teachers.col("class").gt(2)).or(teachers.col("grade").lt(2))).show(3)
    teachers.where(teachers.col("grade").gt(2).and(teachers.col("class").gt(2)).or(teachers.col("grade").lt(2))).show(3)
```

Exception Info

```
Test ----> FILTER
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 5
        at org.apache.spark.sql.catalyst.CatalystTypeConverters$.convertRowWithConverters(CatalystTypeConverters.scala:348)
        at org.apache.spark.sql.catalyst.CatalystTypeConverters$$anonfun$createToScalaConverter$4.apply(CatalystTypeConverters.scala:301)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeTake$2.apply(SparkPlan.scala:150)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeTake$2.apply(SparkPlan.scala:150)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:108)
        at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:150)
        at org.apache.spark.sql.execution.Limit.executeCollect(basicOperators.scala:125)
        at org.apache.spark.sql.DataFrame.collect(DataFrame.scala:1255)
        at org.apache.spark.sql.DataFrame.head(DataFrame.scala:1189)
        at org.apache.spark.sql.DataFrame.take(DataFrame.scala:1248)
        at org.apache.spark.sql.DataFrame.showString(DataFrame.scala:176)
        at org.apache.spark.sql.DataFrame.show(DataFrame.scala:331)
        at DataFrameTest.main(DataFrameTest.java:50)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:664)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:169)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:192)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:111)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by xinyunh** [comment]
Fixed and merged into master(https://github.com/Huawei-Spark/SparkSQL-on-HBase/commit/4ca5e5ceb83120904812b47e177699cd6fbdb0a9)

Thank!
