### ISSUE TITLE
[python] function.pow get  ValueError: could not convert string to float

### ISSUE THREAD

**Issue by pzzs** [Huawei-Spark/hbase#20]
I test it using sqlContext and i get this error also. Maybe it is a bug of Spark.

[1] Hbase Table 

```
grade            int
class            int
subject          string  
teacher _name    string
teacher _age     int

keyCols : grade,class,subject
```

SQL ：
···
CREATE TABLE spark_teacher_3key(grade int, class int, subject string, teacher_name string, teacher_age int, PRIMARY KEY (grade, class, subject)) MAPPED BY (hbase_teacher_3key, COLS=[teacher_name=teacher.name, teacher_age=teacher.age]);
···

Data

```
1,1,subject_1,teacher_1_1_1,25
1,1,subject_2,teacher_1_2_1,25
1,1,subject_3,teacher_1_3_1,25
1,1,subject_4,teacher_1_4_1,25
1,1,subject_5,teacher_1_5_1,25
1,2,subject_1,teacher_1_1_1,25
1,2,subject_2,teacher_1_2_1,25
1,2,subject_3,teacher_1_3_1,25
1,2,subject_4,teacher_1_4_1,25
1,2,subject_5,teacher_1_5_1,25
1,3,subject_1,teacher_1_1_1,25
1,3,subject_2,teacher_1_2_1,25
...
...
```

Python code

```
from pyspark.sql import functions as F
teachers = hsqlContext.sql("Select * from spark_teacher_3key_df")
teachers.select(F.pow('grade', 'class'), F.pow('teacher_age', 2.0)).show(1)
```

Exceptin Info

```
HBaseSQLContext available as hsqlContext.
>>> from pyspark.sql import functions as F
>>> teachers = hsqlContext.sql("Select * from spark_teacher_3key_df")
>>> teachers.select(F.pow('grade', 'class'), F.pow('teacher_age', 2.0)).show(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/cluster/SparkOnHabase/spark/python/pyspark/sql/functions.py", line 67, in _
    jc = getattr(sc._jvm.functions, name)(col1._jc if isinstance(col1, Column) else float(col1),
ValueError: could not convert string to float: grade
>>> 
```

**Comment by xinyunh** [comment]
@DoingDone9 it seems to be the problem of SparkSQL. I test the same data and SQL in its general sqlContext(which is HiveContext) and get the same error.
