### ISSUE TITLE
occur java.lang.RuntimeException when test TPC-DS 95

### ISSUE THREAD

**Issue by hoffmann99** [Huawei-Spark/hbase#21]
[HBASE table]

```
rowNum           int
people_name        string
people_age          int
school_identification  string
school_director       string
```

```
grade         int
class          int
subject        String  
teacher _name        string
teacher _age          int
```

[SQL]

```

CREATE TABLE spark_teacher_3key(grade int, class int, subject string, teacher_name string, teacher_age int, PRIMARY KEY (grade, class, subject)) MAPPED BY (hbase_teacher_3key, COLS=[teacher_name=teacher.name, teacher_age=teacher.age]);

CREATE TABLE spark_people(rowNum int, people_name string, people_age int, school_identification string, school_director string, PRIMARY KEY (rowNum))
MAPPED BY (hbase_people, COLS=[people_name=people.name, people_age=people.age, school_identification=school.identification, school_director=school.director]);
```

Data

```
spark_teacher_3key:
1,1,subject_1,teacher_1_1_1,25
1,1,subject_2,teacher_1_2_1,25
1,1,subject_3,teacher_1_3_1,25
1,1,subject_4,teacher_1_4_1,25
1,1,subject_5,teacher_1_5_1,25
1,2,subject_1,teacher_1_1_1,25
1,2,subject_2,teacher_1_2_1,25
1,2,subject_3,teacher_1_3_1,25
1,2,subject_4,teacher_1_4_1,25
1,2,subject_5,teacher_1_5_1,25
1,3,subject_1,teacher_1_1_1,25
1,3,subject_2,teacher_1_2_1,25

spark_people:
[1,xiaoming,16,id_1,teacherW]
[2,xiaoming,16,id_2,teacherW]
[3,xiaoming,16,id_3,teacherW]
[4,xiaoming,16,id_4,teacherW]
[5,xiaoming,16,id_5,teacherW]
[6,xiaoming,16,id_6,teacherW]
[7,xiaoming,16,id_7,teacherW]
[8,xiaoming,16,id_8,teacherW]
[9,xiaoming,16,id_9,teacherW]
[10,xiaoming,16,id_10,teacherW]
```

```
[SQL]
 select t1.grade,t1.teacher_name from
 (
 select grade,class,subject,teacher_name,teacher_age from spark_teacher_3key where teacher_age between 1 and 10 and class <> 10
 )t1, spark_people t2
where  t1.teacher_name = t2.people_name order by t1.grade;
```

```
[Exception]
java.lang.RuntimeException: [5.40] failure: ``union'' expected but `;' found

where  t1.teacher_name = t2.people_name;
                                       ^
    at scala.sys.package$.error(package.scala:27)
    at org.apache.spark.sql.catalyst.AbstractSparkSQLParser.parse(AbstractSparkSQLParser.scala:36)
    at org.apache.spark.sql.hbase.HBaseSQLDialect.parse(HBaseSQLDialect.scala:28)
    at org.apache.spark.sql.SQLContext$$anonfun$2.apply(SQLContext.scala:145)
    at org.apache.spark.sql.SQLContext$$anonfun$2.apply(SQLContext.scala:145)
    at org.apache.spark.sql.SparkSQLParser$$anonfun$org$apache$spark$sql$SparkSQLParser$$others$1.apply(SparkSQLParser.scala:95)
    at org.apache.spark.sql.SparkSQLParser$$anonfun$org$apache$spark$sql$SparkSQLParser$$others$1.apply(SparkSQLParser.scala:94)
    at scala.util.parsing.combinator.Parsers$Success.map(Parsers.scala:136)
    at scala.util.parsing.combinator.Parsers$Success.map(Parsers.scala:135)
    at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:242)
    at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:242)
    at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
    at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1$$anonfun$apply$2.apply(Parsers.scala:254)
    at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1$$anonfun$apply$2.apply(Parsers.scala:254)
    at scala.util.parsing.combinator.Parsers$Failure.append(Parsers.scala:202)
    at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
    at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
```

**Comment by hoffmann99** [comment]
I think the analyzer have some problem.
sometimes this problem happens.

**Comment by hoffmann99** [comment]
@xinyunh  @yzhou2001  I found where the problem is.
when blank exists before SQL, this problem happens.
I think we should fix this problem, and I close this problem now.
