### ISSUE TITLE
java.util.NoSuchElementException: key not found: encodingFormat

### ISSUE THREAD

**Issue by xuzhiliang** [Huawei-Spark/hbase#23]
Hi,
I am using the branch master, and  my environment is the following
hbase 1.0.0-cdh5.4.5
hadoop 2.6.0-cdh5.4.5
spark 1.4

I have inserted a set of rows in Hbase:

hbase(main):010:0> scan 'student'
ROW                                                                  COLUMN+CELL  
 001                                                                 column=info:age, timestamp=1442818336941, value=20  
 001                                                                 column=info:name, timestamp=1442818355863, value=test01  
 002                                                                 column=info:age, timestamp=1442818367948, value=21  
 002                                                                 column=info:name, timestamp=1442818382205, value=test02  
2 row(s) in 0.0150 seconds

i try in hbase-sql shell,it works well.
CREATE TABLE student (
id STRING,
age STRING,
name STRING,
PRIMARY KEY (id)) 
MAPPED BY (student,COLS=[age=info.age, name=info.name]);

the result of 'select \* from student;'
+---+---+------+
| id|age|  name|
+---+---+------+
|001| 20|test01|
|002| 21|test02|
+---+---+------+

but i try in the spark-shell,it occurs error.

scala> import org.apache.spark.sql.hbase._
import org.apache.spark.sql.hbase._

scala> val hbaseContext =  new HBaseSQLContext(sc)
hbaseContext: org.apache.spark.sql.hbase.HBaseSQLContext = org.apache.spark.sql.hbase.HBaseSQLContext@29e2f29e

scala> hbaseContext.read.format("org.apache.spark.sql.hbase.HBaseSource").options(
     |     Map("namespace" -> "", "tableName" -> "student", "hbaseTableName" -> "student",
     |       "colsSeq" -> "id,age,name",
     |       "keyCols" -> "id,string",
     |       "nonKeyCols" ->  "age,string,info,age;name,string,info,name")).load
java.util.NoSuchElementException: key not found: encodingFormat
  at scala.collection.MapLike$class.default(MapLike.scala:228)
  at org.apache.spark.sql.sources.CaseInsensitiveMap.default(ddl.scala:463)
  at scala.collection.MapLike$class.apply(MapLike.scala:141)
  at org.apache.spark.sql.sources.CaseInsensitiveMap.apply(ddl.scala:463)
  at org.apache.spark.sql.hbase.HBaseSource.createRelation(HBaseRelation.scala:50)
  at org.apache.spark.sql.sources.ResolvedDataSource$.apply(ddl.scala:265)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:114)
  at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:34)
  at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:39)
  at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:41)
  at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:43)
  at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:45)
  at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:47)
  at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:49)
............

need your help,thinks?

**Comment by xinyunh** [comment]
@xuzhiliang 

Sorry for the late response. 
This is backup repository, so please change it to our official site:
https://github.com/Huawei-Spark/Spark-SQL-on-HBase

Since it is a pre-exisit table, we need to add "IN StringFormat" at the end of the create command.

And for now, I don't think we support reading data via HBaseSource.
Thus, if you want get the data from hbase, you might run:
hbaseContext.sql("select \* from student")
